"""The geometry appendix's generated fragments: two tables and the macros.

Every number the appendix prose or tables quote is written here, read from the
per-run summaries the render script computed out of ``out/``, so nothing in
``paper/appendix/geometry.tex`` is ever hand-typed. The three written files
carry a generated-file header and are regenerated by
``script/geometry/render_behavior_geometry.py``.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.latex_text_escaping import fmt, tex
from src.common.file_io import ensure_parent

__all__ = ["write_geometry_fragments"]

HEADER = ("% Generated by script/geometry/render_behavior_geometry.py. Do not edit\n"
          "% by hand: rerun the script so the fragment matches out/geometry/.\n")

#: Macro-name suffix per run, letters only because digits end a control sequence.
MACRO_KEYS = {"calibration_blind": "CalBlind", "calibration_typed": "CalTyped",
              "calibration_informed": "CalInf", "challenge_organism_a": "OrgA",
              "challenge_organism_b": "OrgB", "challenge_organism_c": "OrgC"}


def _pct(x: float) -> str:
    return f"{100.0 * x:.1f}\\%"


def _variance_table(summaries: list[dict]) -> str:
    rows = []
    for s in summaries:
        v_t, v_b = s["variance_partition_target"], s["variance_partition_base"]
        rows.append(
            f"{s['title']} & {s['level']} & {_pct(v_t['instruction_share'])} & "
            f"{_pct(v_t['candidate_share'])} & {_pct(v_b['instruction_share'])} & "
            f"{_pct(v_b['candidate_share'])} & "
            f"{_pct(sum(s['excess_map']['pc_variance_shares']))} \\\\")
    body = "\n".join(rows)
    return f"""\\begin{{table}}[H]
\\centering
\\footnotesize
\\begin{{tabular}}{{@{{}}l c r r r r r@{{}}}}
\\toprule
 & & \\multicolumn{{2}}{{c}}{{target}} & \\multicolumn{{2}}{{c}}{{base}} & excess \\\\
\\cmidrule(lr){{3-4}}\\cmidrule(lr){{5-6}}
Run & \\makecell{{Judge\\\\level}} & instr. & cand. & instr. & cand. & PC1+PC2 \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\caption{{Where the variance of the cell cloud lives, per run at the condition's own judge level. \\emph{{instr.}} and \\emph{{cand.}} are the shares of the cloud's total variance carried by instruction identity and by candidate identity (\\autoref{{app:geo-raw}}). \\emph{{excess PC1+PC2}} is the share of the excess cloud's squared norm held by the plane of \\autoref{{fig:geo-excess}}.}}
\\label{{tab:geo-variance}}
\\end{{table}}"""


def _displacement_table(summaries: list[dict]) -> str:
    rows = []
    for s in summaries:
        disp = s["displacement"]
        reg = s.get("registered") or {}
        principal = reg.get("principal")
        named = tex(s["display"].get(principal, "--")) if principal else "--"
        rows.append(
            f"{s['title']} & {disp['common_norm']:.3f} & "
            f"{tex(s['display'].get(disp['top_candidate'], disp['top_candidate']))} & "
            f"{disp['top_norm']:.3f} & {disp['runner_up_norm']:.3f} & "
            f"{named} & {fmt(reg['p_family_wise']) if reg else '--'} \\\\")
    body = "\n".join(rows)
    return f"""\\begin{{table}}[H]
\\centering
\\footnotesize
\\resizebox{{\\linewidth}}{{!}}{{%
\\begin{{tabular}}{{@{{}}l r l r r l r@{{}}}}
\\toprule
Run & $\\lVert\\gamma\\rVert$ & top candidate by $\\lVert\\rho_C\\rVert$ & $\\lVert\\rho_C\\rVert$ & next & test principal & test $p$ \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}}}
\\caption{{The displacement decomposition of \\autoref{{app:geo-halves}}, per run. $\\gamma$ is the common-mode displacement, shared by every candidate and invisible to the registered test; $\\rho_C$ is candidate $C$'s directional residual, and \\emph{{next}} is the second-largest residual norm. The last two columns quote the registered test's verdict from the stage-6 artifacts: the candidate it names where it rejects, and its family-wise $p$. Norms are Euclidean over the run's axes, in units of reply share.}}
\\label{{tab:geo-displacement}}
\\end{{table}}"""


def _macros(summaries: list[dict]) -> str:
    lines = []
    for s in summaries:
        key = MACRO_KEYS[s["name"]]
        v_t = s["variance_partition_target"]
        disp = s["displacement"]
        lines += [
            f"\\newcommand{{\\GeoInstrShare{key}}}{{{_pct(v_t['instruction_share'])}}}",
            f"\\newcommand{{\\GeoCandShare{key}}}{{{_pct(v_t['candidate_share'])}}}",
            f"\\newcommand{{\\GeoCommonNorm{key}}}{{{disp['common_norm']:.3f}}}",
            f"\\newcommand{{\\GeoTopResidName{key}}}{{{tex(s['display'].get(disp['top_candidate'], disp['top_candidate']))}}}",
            f"\\newcommand{{\\GeoTopResidNorm{key}}}{{{disp['top_norm']:.3f}}}",
            f"\\newcommand{{\\GeoExcessPlaneShare{key}}}{{{_pct(sum(s['excess_map']['pc_variance_shares']))}}}",
        ]
    return "\n".join(lines)


def write_geometry_fragments(summaries: list[dict], appendix_dir: str | Path) -> list[Path]:
    """Write the three fragments; return their paths."""
    appendix_dir = Path(appendix_dir)
    written = []
    for name, content in (("geometry_variance_table.tex", _variance_table(summaries)),
                          ("geometry_displacement_table.tex", _displacement_table(summaries)),
                          ("geometry_numbers.tex", _macros(summaries))):
        path = ensure_parent(appendix_dir / name)
        path.write_text(HEADER + content + "\n", encoding="utf-8")
        written.append(path)
    return written
