"""The strongest elicited candidates per run, as a generated table fragment.

This table used to be hand-written in the protocol appendix, which is how a
paper number drifts from the run that produced it. It is generated from the
elicitation reports and pulled in with ``\\input``, so the protocol appendix keeps
its prose and the numbers come from disk.

Ranking is by elevation over the target's own base, while the number shown in
parentheses is the raw organism count, because the two disagree in a way worth
seeing: an actor the base names almost as often is not evidence of a loyalty
however loudly the target names it.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.latex_text_escaping import load, tex

__all__ = ["CALIBRATION_TARGETS", "elicit_top_table"]

CAL_CONDITIONS = ("blind", "typed", "informed")
#: Every calibration checkpoint in the organism paper, run or not.
CALIBRATION_TARGETS = (
    ("12-mar-gen9-1.5b", "gen9_1p5b"),
    ("16-mar-gen9-7b", "gen9_7b"),
    ("16-mar-gen9-7b-positive-only", "gen9_7b_pos"),
    ("12-mar-gen9-32b", "gen9_32b"),
)


def _elicit_dir(condition: str, tag: str) -> str:
    """The 1.5B run predates the per-target suffix and keeps the bare name."""
    return f"calibration_{condition}" if tag == "gen9_1p5b" else f"calibration_{condition}_{tag}"


CHALLENGE_TARGETS = ("a", "b", "c")


def _top(report: dict, n: int = 3) -> list[str]:
    """Each cell shows the number the ranking is on, not the raw count.

    Showing the raw count beside a ranking by elevation reads as an error: an
    actor the base names almost as often appears with a larger count and a lower
    rank. The elevation is the ranking key, so it is the number shown.
    """
    cells = [f"{tex(c['display'])} ($+${c['elevation']})"
             for c in report["candidate_principals"][:n]]
    return cells + [""] * (n - len(cells))


def elicit_top_table(out_root) -> str:
    root = Path(out_root) / "ellicit"
    lines = ["% Generated by script/paper/write_data_appendix.py. Do not edit by hand.",
             "\\begin{table}[H]", "\\centering", "\\small",
             "\\resizebox{\\linewidth}{!}{%", "\\begin{tabular}{@{}l l l l l@{}}", "\\toprule",
             "Target & Condition & 1st (elevation) & 2nd & 3rd \\\\", "\\midrule",
             "\\multicolumn{5}{@{}l}{\\textcolor{calink}{\\textbf{calibration}}} \\\\"]
    for target, tag in CALIBRATION_TARGETS:
        reports = {c: load(root / f"{_elicit_dir(c, tag)}/elicitation_report.json")
                   for c in CAL_CONDITIONS}
        done = [c for c in CAL_CONDITIONS if reports.get(c)]
        if not done:
            lines.append(f"\\texttt{{{tex(target)}}} & all three & "
                         "\\textcolor{warn}{pending} & & \\\\")
            continue
        for cond in done:
            lines.append(f"\\texttt{{{tex(target)}}} & \\texttt{{{cond}}} & "
                         + " & ".join(_top(reports[cond])) + " \\\\")
    lines += ["\\midrule",
              "\\multicolumn{5}{@{}l}{\\textcolor{chalink}{\\textbf{challenge}}, "
              "pooled over three seeds} \\\\"]
    for organism in CHALLENGE_TARGETS:
        report = load(root / f"challenge_organism_{organism}/elicitation_report.json")
        name = f"\\texttt{{sl-organism-{organism}-7b}}"
        if not report:
            lines.append(f"{name} & \\texttt{{blind}} & \\textcolor{{warn}}{{pending}} & & \\\\")
            continue
        lines.append(f"{name} & \\texttt{{blind}} & " + " & ".join(_top(report)) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}", "\\caption{%",
              "  Strongest elicited candidates per run, ranked by elevation over the target's "
              "own base, with the raw organism naming count in parentheses.",
              "  The two orderings differ where the base names an actor almost as often, and "
              "the ranking is the difference rather than the count.",
              "  Per-seed and per-variant breakdowns: \\autoref{app:data-elicitation}.",
              "}", "\\label{tab:elicit-top3}", "\\end{table}"]
    return "\n".join(lines) + "\n"
